#!/usr/bin/env python3
"""Create a master .tex by concatenating chapter .tex files in order.

Usage:
    python scripts/build_master_tex.py
    python scripts/build_master_tex.py --chapters thesis/chapters --out thesis/master.tex
"""

from pathlib import Path
import argparse
import re

RE_NUM = re.compile(r"^\s*(\d+)")


def find_number_prefix(name: str):
    m = RE_NUM.match(name)
    return int(m.group(1)) if m else None


def sort_key(path: Path):
    name = path.name
    num = find_number_prefix(name)
    if num is not None:
        return (0, num, name)
    return (1, name.lower())


def build_master(chapters_dir: Path, out_file: Path):
    chapters_dir = chapters_dir.expanduser().resolve()
    if not chapters_dir.exists() or not chapters_dir.is_dir():
        raise SystemExit(f"Chapters directory not found: {chapters_dir}")

    files = sorted([p for p in chapters_dir.glob("*.tex") if p.is_file()], key=sort_key)
    if not files:
        raise SystemExit(f"No .tex files found in {chapters_dir}")

    out_file.parent.mkdir(parents=True, exist_ok=True)

    with out_file.open("w", encoding="utf-8") as out:
        out.write("% master.tex generated by scripts/build_master_tex.py\n")
        out.write(f"% source folder: {chapters_dir}\n\n")

        for p in files:
            out.write(f"% ---- {p.name} ----\n")
            content = p.read_text(encoding="utf-8")
            out.write(content.rstrip() + "\n\n")

    print(f"Wrote {out_file} (concatenated {len(files)} files)")


def main():
    parser = argparse.ArgumentParser(
        description="Build master.tex from chapter .tex files"
    )
    parser.add_argument(
        "--chapters",
        default="thesis/chapters",
        help="directory with chapter .tex files",
    )
    parser.add_argument(
        "--out", default="thesis/master.tex", help="output master .tex file"
    )
    args = parser.parse_args()

    build_master(Path(args.chapters), Path(args.out))


if __name__ == "__main__":
    main()
